try{
    console.log(Não);
}catch(erro){
    console.log('não deu erro')
}